#!/bin/bash

# Alex Florescu, alexf @ adminfactory.net
# This check is intended for nagios / nrpe. Available arguments are: role, keys
# For nrpe, edit nrpe.cfg and define like so:
# command[check_tcp_conn]=/usr/lib/nagios/plugins/check_tcp_conn

COM=$(netstat -st|awk '/connections established/ {print $1}')

        if [ $COM -lt 1000 ];
                then echo "OK - Current TCPs: $(echo $COM)"
                exit 0

        # The following elif order is important!
        elif [[ $COM -gt 1500 ]];
                then echo "CRITICAL - Current TCPs: $(echo $COM)"
                exit 2

        elif [ $COM -gt 1000 ];
                then echo "WARNING - Current TCPs: $(echo $COM)"
                exit 1

        else echo "Unknown output: $(echo "$COM")"
                exit 2
    fi
